### ISSUE TITLE
vehiculos 

### ISSUE THREAD

**Issue by mml22** [edgararuiz/taller-tidyverse#11]
## Explorar datos

1. Cargar datos en una variable
```{r}
actuales<- vehiculos
```
Error in loadNamespace(name) : there is no package called ‘fueleconomy’

___
A pesar que utilice primero el instalar-paquetes y no me dio ningún error, no me instalo 'fueleconomy' por alguna razón.

**Comment by mml22** [comment]
Lo puedo correr solo al instalar 'fueleconomy'

**Comment by edgararuiz-zz** [comment]
Que pasa cuando pasas: `library(fueleconomy)`?

**Comment by mml22** [comment]
Me da un error de que no tengo el paquete instalado. El problema esta en que el install.packages no me funciono por ende no me instalo ese package.

**Comment by edgararuiz-zz** [comment]
Fixed 1a90acd44c5d234344f9265c50e82e325ccdd47b
