### ISSUE TITLE
fechas

### ISSUE THREAD

**Issue by RaymondLTremblay** [edgararuiz/taller-tidyverse#12]
En la siguiente parte yo añadi código para hacer una grafica, pq siempre he tenido problema con el s4 vs el s3 y quería ver si funcionaba.   Pero no funciona el código de abajo.  

Creo que seria bien hablar de la diferencia entre s3 y s4, pq ya es mas y mas común el uso de s4 en lo packages.  y como se usa para hacer análisis y gráficas.  

nueva_fechas %>%
  mutate(desde_hoy = as.duration(fecha %--% today())) %>%
  filter(desde_hoy > dweeks(10)) %>%
  ggplot() +
  geom_col(aes(codigo, desde_hoy)) +
  coord_flip()

**Comment by edgararuiz-zz** [comment]
No si este es un problema con S3/S4, creo que es simplemente que `aes()` espera un vector de tipo numerico of alfanumerico.  Si agrega `int_length()` a `desde_hoy` funciona su grafica:

```r
nueva_fechas %>%
  mutate(desde_hoy = as.duration(fecha %--% today())) %>%
  filter(desde_hoy > dweeks(10)) %>%
  ggplot() +
  geom_col(aes(codigo, int_length(desde_hoy))) +
  coord_flip()
```

**Comment by RaymondLTremblay** [comment]
Este "int_length". nunca lo había visto antes.   

Gracias

**Comment by edgararuiz-zz** [comment]
Por eso es parte de la clase ;) 

https://github.com/edgararuiz/taller-tidyverse/blob/0061165665d44f6b2849bd4d1dfa62f8439c1f42/ejercicios/fechas.Rmd#L88-L96
