### ISSUE TITLE
instalar_packages

### ISSUE THREAD

**Issue by mml22** [edgararuiz/taller-tidyverse#2]
**Error in install.packages : Updating loaded packages**
> rm(check_versions, installed_packages, packages, check_for, to_install, update_packages, check_package)

Restarting R session...

> install.packages(update_packages)
**Error in install.packages : object 'update_packages' not found**

**Comment by RaymondLTremblay** [comment]
When I tried to re-install it just kept going, going and going....  I restarted and then all the files showed up

**Comment by RaymondLTremblay** [comment]
I've been working with the previous version, I've not been able to update to the new version.

**Comment by edgararuiz-zz** [comment]
@RaymondLTremblay / @mml22 - Por favor use: `usethis::use_course("bit.ly/upr-tidyverse")` para bajar la version mas reciente
