### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by RaymondLTremblay** [edgararuiz/taller-tidyverse#20]
What does suppressMessages do in this case.  I tried it without the function I did not see any difference in the output. 

suppressMessages(library(ggplot2)) # message what supressMessages What does it do?
ggplot() +
  geom_histogram(aes(ciudad), data = millas, bins = 10)

**Comment by edgararuiz-zz** [comment]
`ggplot2` had been displaying override method messages in a manner that I'd rather just prevent:

```
## Registered S3 methods overwritten by 'ggplot2':
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang
```
