### ISSUE TITLE
Agregando modelos

### ISSUE THREAD

**Issue by RaymondLTremblay** [edgararuiz/taller-tidyverse#3]
Despues de enseñar como hacer la gráfica básica con lm, se puede demostrar como visualizar multiples modelos. Enfatizando la sencillez del proceso.  
añadiendo "color=claridad"

ggplot(data = diamantes, aes(precio, quilate, color=claridad)) +
  geom_point(aes(color = claridad), alpha = 0.3) +
  geom_smooth(method = "lm") +
  theme_minimal()

**Comment by edgararuiz-zz** [comment]
No entiendo que es el cambio que esta sugiriendo aqui

**Comment by RaymondLTremblay** [comment]
Estoy sugiriendo que se puede enseñar como agregar multiples modelos en una gráfica
 aqui tenemos un modelo lineal, x^3 y log.


ggplot(data = diamantes, aes(precio, quilate)) +
geom_point(aes(color = claridad), alpha = 0.3) +
geom_smooth(method = "lm", color="pink") +
geom_smooth(method="lm",
formula=ypoly(x,3), color="red")+
geom_smooth(method="lm",
formula=ylog(x), color="blue")+
geom_smooth(color="black")+ # LOESS
theme_minimal()

**Comment by edgararuiz-zz** [comment]
De que paquete proviene `ypoly`?

**Comment by RaymondLTremblay** [comment]
Sorry, it did not paste correctly


formula=y~poly(x,3), color="red")+
geom_smooth(method="lm",
formula=y~log(x), color="blue")+

**Comment by RaymondLTremblay** [comment]
Again there is a problem, there should be a tilde between the y and the poly 

y ~ poly

**Comment by RaymondLTremblay** [comment]
If you put the tilde directly after the poly it gives you a line across the whole text.

**Comment by edgararuiz-zz** [comment]
Oh ok, I'm getting this error:

```r
library(ggplot2)
ggplot(data = datos::diamantes , aes(precio, quilate)) +
geom_point(aes(color = claridad), alpha = 0.3) +
geom_smooth(method = "lm", color="pink") +
geom_smooth(method="lm", formula=~poly(x,3), color="red")

#> Warning: Computation failed in `stat_smooth()`:
#> incompatible dimensions
```

**Comment by RaymondLTremblay** [comment]
You forgot the "y" before the = 

library(ggplot2)
ggplot(data = datos::diamantes , aes(precio, quilate)) +
geom_point(aes(color = claridad), alpha = 0.3) +
geom_smooth(method = "lm", color="pink") +
geom_smooth(method="lm", formula=~poly(x,3), color="red")

**Comment by RaymondLTremblay** [comment]
Before the tilde. not the =.
