### ISSUE TITLE
map_data. wrong spelling

### ISSUE THREAD

**Issue by RaymondLTremblay** [edgararuiz/taller-tidyverse#7]
One of the islands of Puerto Rico is misspelled in the data file. It is written "Viaques", when. it should be Vieques.
pr <- map_data("world", region = "Puerto Rico").  

![Screenshot 2019-07-24 19 46 20](https://user-images.githubusercontent.com/29467955/61835956-03711180-ae4c-11e9-928a-3ab9bbc5f7dd.png)

**Comment by RaymondLTremblay** [comment]
Isla Mona correct name is "Isla de la Mona"

**Comment by edgararuiz-zz** [comment]
Estos datos vienen del paquete `maps`, asi que no lo puedo cambiar.  

Si quiere, puede reportarlo aqui: https://github.com/adeckmyn/maps

**Comment by RaymondLTremblay** [comment]
okay ya ke escribi
